[workspace]

resolver = "2"

members = [
    "utils",
    "misc",
    "bigint",
    "rsa",
    "ciphers",
    "ecdsa",
    "hash",
    "vrf",
]

[patch."http://github.com/davxy/ark-ecvrf"]
ark-ecvrf = { path = "/home/davxy/develop/projs/ark-ecvrf" }
