[workspace]

resolver = "2"

members = [
    "utils",
    "misc",
    "bigint",
    "rsa",
    "ciphers",
    "ecdsa",
    "hash",
    "vrf",
]

# [patch."http://github.com/davxy/ark-ec-vrfs"]
# ark-ec-vrfs = { path = "/home/davxy/develop/projs/ark-ec-vrfs" }
