[package]
name = "vrf"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
utils = { path = "../utils" }
criterion = "0.5.1"
rand = "0.8.5"
blake2 = "0.10.6"
merlin = "3.0.0"
schnorrkel = "0.11.5"
ark-vrf = { version = "0.5.3", features =["full","parallel","asm"] }
ark-std = "0.6.0"
ark-ed-on-bls12-381-bandersnatch = "0.6.0"

[[bench]]
name = "vrfs"
harness = false

[[bench]]
name = "ring-vrfs"
harness = false
