[package]
name = "bigint"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"
utils = { path = "../utils" }
primitive-types = "0.12.2"
crypto-bigint = "0.5.5"
num = "0.4.1"
cry-rs = { git = "https://github.com/davxy/cry-rs" }

[[bench]]
name = "bigint"
harness = false
